services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=cartedb'
      - 'MONGO_INITDB_ROOT_PASSWORD='
      - 'MONGO_INITDB_ROOT_USERNAME='
    ports:
      - '27017:27017'
  config:
    image: 'config:0.0.1-SNAPSHOT'
    environment:
      - 'CONFIG_SERVER_SEARCH_LOCATIONS=${CONFIG_SERVER_SEARCH_LOCATIONS}'
      - 'CONFIG_SERVER_BUCKET=${CONFIG_SERVER_BUCKET}'
      - 'CONFIG_SERVER_REGION=${CONFIG_SERVER_REGION}'
      - 'CONFIG_SERVER_SECURITY_USERNAME=${CONFIG_SERVER_SECURITY_USERNAME}'
      - 'CONFIG_SERVER_SECURITY_PASSWORD=${CONFIG_SERVER_SECURITY_PASSWORD}'
      - 'CONFIG_SERVER_AWS_ACCESS_KEY=${CONFIG_SERVER_AWS_ACCESS_KEY}'
      - 'CONFIG_SERVER_AWS_SECRET_KEY=${CONFIG_SERVER_AWS_SECRET_KEY}'
    ports:
      - '8888:8888'